version: '3'

services:
  tomcat:
    image: tomcat
    ports:
      - "8000:8080"

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: videogames
      MYSQL_USER: user
      MYSQL_PASSWORD: password
