version: '3'

services:
  tomcat:
    build: ./tomcat
    ports:
      - "8000:8080"
    volumes:
      - ./tomcat:/usr/local/tomcat/webapps/videogamesearch

  mysql:
    build: ./sql
    restart: always

volumes:
  db_data: